### ISSUE TITLE
It's possible add floating labels

### ISSUE THREAD

**Issue by jesusferm** [DJ-Raven/java-swing-suffix-predix-con#1]
It's possible add floating labels over border like input text Google login?

And if it's possible you have a example? Thanks. 

![IMG_20231106_094404_413](https://github.com/DJ-Raven/java-swing-suffix-predix-con/assets/5892507/68eea25a-d93a-4b0c-ac68-c0c444f9f694)

**Comment by DJ-Raven** [comment]
This project don't have placeholder, but you can try with this [RP](https://github.com/DJ-Raven/raven-project) as jtextfield custom

**Comment by jesusferm** [comment]
Thanks!
